RecipeCategory.find_by(name:"Salty Breakfast").update(order_hint: 0)
RecipeCategory.find_by(name:"Sweet Breakfast").update(order_hint: 0.3)
RecipeCategory.find_by(name:"Midday Meal").update(order_hint: 0.4)
RecipeCategory.find_by(name:"Evening Meal").update(name: "Children Evening Meal", order_hint: 0.6)
RecipeCategory.find_by(name:"Other").update(order_hint: 1)
RecipeCategory.find_by(name:"Sandwitches").update(name: "Adult Breakfast", order_hint: 0.2)
RecipeCategory.find_by(name:"One Dick").update(name: "Adult Evening Meal", order_hint: 0.8)


ProductCategory.find_by(name:"1new").update(name:"new", order_hint: 0)
ProductCategory.find_by(name:"2bread").update(name:"bread", order_hint: 0.1)
ProductCategory.find_by(name:"3vegetables").update(name:"vegetables", order_hint: 0.15)
ProductCategory.find_by(name:"4fruit").update(name:"fruit", order_hint: 0.2)
ProductCategory.find_by(name:"5oils").update(name:"oils", order_hint: 0.25)
ProductCategory.find_by(name:"6spices").update(name:"spices", order_hint: 0.3)
ProductCategory.find_by(name:"7cans and jars").update(name:"cans and jars", order_hint: 0.35)
ProductCategory.create(name:"candy", order_hint: 0.4)
ProductCategory.find_by(name:"8vegan").update(name:"vegan", order_hint: 0.5)
ProductCategory.find_by(name:"9prepared food").update(name:"prepared food", order_hint: 0.55)
ProductCategory.find_by(name:"10meat").update(name:"meat", order_hint: 0.6)
ProductCategory.find_by(name:"11fish").update(name:"fish", order_hint: 0.65)
ProductCategory.find_by(name:"12dairy").update(name:"dairy", order_hint: 0.7)
ProductCategory.find_by(name:"13frozen food").update(name:"frozen food", order_hint: 0.75)
ProductCategory.find_by(name:"14loose").update(name:"loose", order_hint: 0.8)
ProductCategory.find_by(name:"15warm beverages").update(name:"warm beverages", order_hint: 0.85)
ProductCategory.find_by(name:"16cold drinks").update(name:"cold drinks", order_hint: 0.9)
ProductCategory.find_by(name:"17cleaning agents").update(name:"cleaning agents", order_hint: 0.95)
ProductCategory.find_by(name:"18hygiene products").update(name:"hygiene products", order_hint: 1)

ShoppingList.all.each do |s|
  s.update(order_hint: ProductCategory.find_by(id: 1).order_hint)
end