AllProduct.find_by(category:"1new").update(category:"new")
AllProduct.find_by(category:"2bread").update(category:"bread")
AllProduct.find_by(category:"3vegetables").update(category:"vegetables")
AllProduct.find_by(category:"4fruit").update(category:"fruit")
AllProduct.find_by(category:"5oils").update(category:"oils")
AllProduct.find_by(category:"6spices").update(category:"spices")
AllProduct.find_by(category:"7cans and jars").update(category:"cans and jars")
AllProduct.find_by(category:"8vegan").update(category:"vegan")
AllProduct.find_by(category:"9prepared food").update(category:"prepared food")
AllProduct.find_by(category:"10meat").update(category:"meat")
AllProduct.find_by(namcategorye:"11fish").update(category:"fish")
AllProduct.find_by(category:"12dairy").update(category:"dairy")
AllProduct.find_by(category:"13frozen food").update(category:"frozen food")
AllProduct.find_by(category:"14loose").update(category:"loose")
AllProduct.find_by(category:"15warm beverages").update(category:"warm beverages")
AllProduct.find_by(category:"16cold drinks").update(category:"cold drinks", order_hint: 0.9)
AllProduct.find_by(category:"17cleaning agents").update(category:"cleaning agents")
AllProduct.find_by(category:"18hygiene products").update(category:"hygiene products")