#Recipe Categories create
RecipeCategory.create(name:"Salty Breakfast")
RecipeCategory.create(name:"Sweet Breakfast")
RecipeCategory.create(name:"Midday Meal")
RecipeCategory.create(name:"Evening Meal")

#Product Categories create
ProductCategory.create(name:"1new")
ProductCategory.create(name:"2bread")
ProductCategory.create(name:"3vegetables")
ProductCategory.create(name:"4fruit")
ProductCategory.create(name:"5oils")
ProductCategory.create(name:"6spices")
ProductCategory.create(name:"7cans and jars")
ProductCategory.create(name:"8vegan")
ProductCategory.create(name:"9prepared food")
ProductCategory.create(name:"10meat")
ProductCategory.create(name:"11fish")
ProductCategory.create(name:"12dairy")
ProductCategory.create(name:"13frozen food")
ProductCategory.create(name:"14loose")
ProductCategory.create(name:"15warm beverages")
ProductCategory.create(name:"16cold drinks")
ProductCategory.create(name:"17cleaning agents")
ProductCategory.create(name:"18hygiene products")